// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8yb73mwZ7_rELkT4Tt6zWqTb376J0QM',
    appId: '1:457793812221:web:b416af8ca96b6603253094',
    messagingSenderId: '457793812221',
    projectId: 'plastica-suc',
    authDomain: 'plastica-suc.firebaseapp.com',
    storageBucket: 'plastica-suc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4ZJERi9mFhr1wYvXqPyyqshxy_5Bhp0',
    appId: '1:457793812221:android:8b44a813a5480504253094',
    messagingSenderId: '457793812221',
    projectId: 'plastica-suc',
    storageBucket: 'plastica-suc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9BgOwjzaHRS7sIUiFpBy74QwV0BYmTMQ',
    appId: '1:457793812221:ios:a16afd66a5c73c35253094',
    messagingSenderId: '457793812221',
    projectId: 'plastica-suc',
    storageBucket: 'plastica-suc.firebasestorage.app',
    iosBundleId: 'com.example.plasticaSuc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9BgOwjzaHRS7sIUiFpBy74QwV0BYmTMQ',
    appId: '1:457793812221:ios:a16afd66a5c73c35253094',
    messagingSenderId: '457793812221',
    projectId: 'plastica-suc',
    storageBucket: 'plastica-suc.firebasestorage.app',
    iosBundleId: 'com.example.plasticaSuc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK8yb73mwZ7_rELkT4Tt6zWqTb376J0QM',
    appId: '1:457793812221:web:b4e0f13e0dacb44b253094',
    messagingSenderId: '457793812221',
    projectId: 'plastica-suc',
    authDomain: 'plastica-suc.firebaseapp.com',
    storageBucket: 'plastica-suc.firebasestorage.app',
  );
}
